# Generated by Django 5.1 on 2026-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountantdata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Admindata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coursedata',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('crname', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Installmentdata',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('stid', models.CharField(max_length=100)),
                ('stcrid', models.CharField(max_length=100)),
                ('inst', models.CharField(max_length=100)),
                ('sub_date', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Logindata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photodata',
            fields=[
                ('photo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCoursedata',
            fields=[
                ('st_crid', models.AutoField(primary_key=True, serialize=False)),
                ('stid', models.CharField(max_length=100)),
                ('crname', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('joining', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('stid', models.AutoField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('lastquali', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
