# Generated by Django 5.1 on 2026-03-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accountantdata',
        ),
    ]
