# Generated by Django 5.1 on 2026-03-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_delete_accountantdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherdata',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('crid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
