# Generated by Django 5.1 on 2026-04-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_teacherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='section',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('arid', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=50)),
                ('attendance_date', models.DateField()),
                ('time_slot', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app2.coursedata')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app2.studentdata')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to='app2.teacherdata')),
            ],
            options={
                'unique_together': {('student', 'course', 'attendance_date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='app2.coursedata')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app2.teacherdata')),
            ],
            options={
                'unique_together': {('teacher', 'course', 'section')},
            },
        ),
    ]
