# Generated by Django 5.1 on 2026-04-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_attendance_and_teaching'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='time_slot',
            field=models.CharField(default='9-10', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'course', 'section', 'time_slot')},
        ),
    ]
